version: 1
metadata:
  owner: ai-platform-team
  source: docs/ai-devflow.md
  revised_at: 2025-10-14
stages:
  - id: spec_authoring
    name: Spec Authoring
    description: Collect requirements, draft user stories, and define acceptance criteria.
    actors:
      - role: product_owner
        responsibilities:
          - approve scope
          - align stakeholders
      - role: ai_assistant
        responsibilities:
          - summarize domain context
          - propose user stories
    inputs:
      - type: issue
        format: github
        location: docs/specs/
    outputs:
      - type: markdown
        path: docs/specs/{feature}.md
    gates:
      - type: review
        reviewer: domain_lead
        criteria:
          - coverage_of_requirements
          - dependency_mapping
    pipelines:
      - id: crm-spec
        issue: 295
        artifacts:
          - docs/specs/crm/requirements.md
          - docs/metrics/crm.md
      - id: sales-spec
        issue: 296
        artifacts:
          - docs/specs/sales/requirements.md
          - docs/compliance/sales-ledger.md
      - id: hr-spec
        issue: 297
        artifacts:
          - docs/runbooks/hr-ops.md
          - docs/compliance/hr-privacy.md
      - id: bi-spec
        issue: 298
        artifacts:
          - docs/bi/data-mart.md
          - docs/bi/etl-evaluation.md
  - id: code_generation
    name: Code Generation & Scaffolding
    description: Use Codex CLI templates and project conventions to generate code skeletons.
    actors:
      - role: lead_engineer
        responsibilities:
          - seed repository structure
          - configure CI/CD hooks
      - role: ai_assistant
        responsibilities:
          - produce boilerplate code
          - suggest terraform modules
    inputs:
      - type: template
        source: templates/
    outputs:
      - type: pull_request
        branch_pattern: feature/{id}
    gates:
      - type: automatic_check
        check: lint
      - type: automatic_check
        check: unit_tests
    pipelines:
      - id: crm-module
        branch: feature/phase2-crm-sales-prep
        outputs:
          - services/project-api/src/crm/**
          - shared/ai/conversation/**
      - id: sales-module
        branch: feature/phase2-crm-sales-prep
        outputs:
          - services/project-api/src/sales/**
          - iac/terraform/sales-monitoring/**
      - id: hr-module
        branch: feature/phase2-hr-bi-prep
        outputs:
          - services/project-api/src/hr/**
          - db/seeds/hr/skill-tags.json
      - id: bi-analytics
        branch: feature/phase2-hr-bi-prep
        outputs:
          - docs/bi/**
          - iac/terraform/analytics-observability/**
          - examples/bi/nl-query-poc/**
  - id: test_and_review
    name: Automated Test & AI Review
    description: Execute automated tests and leverage AI reviewers before human approval.
    actors:
      - role: qa_engineer
        responsibilities:
          - define test coverage
          - triage failures
      - role: ai_reviewer
        responsibilities:
          - add PR comments
          - summarize risks
    inputs:
      - type: ci_workflow
        name: pull-request
    outputs:
      - type: report
        path: reports/{pr}.md
    gates:
      - type: ai_review
        provider: copilot
      - type: human_review
        reviewer: module_owner
  - id: documentation
    name: Documentation & Knowledge Share
    description: Ensure docs and runbooks stay in sync with shipped features.
    actors:
      - role: tech_writer
        responsibilities:
          - update runbooks
          - maintain API docs
      - role: ai_assistant
        responsibilities:
          - suggest doc diffs
    inputs:
      - type: repository
        path: docs/
    outputs:
      - type: pages_deploy
        url: https://itdojp.github.io/ITDO_ERP3
    gates:
      - type: doc_checklist
        items:
          - runbook_updated
          - api_diffs_linked
  - id: deployment
    name: Deployment & Observability
    description: Promote changes to staging/production with observability hooks.
    actors:
      - role: sre
        responsibilities:
          - manage terraform apply
          - monitor alarms
      - role: ai_ops
        responsibilities:
          - anomaly detection
          - rollback recommendation
    inputs:
      - type: pipeline
        tool: argo_cd
    outputs:
      - type: release_note
        path: docs/releases/{date}.md
    gates:
      - type: approval
        approver: release_manager
      - type: metric_watch
        thresholds:
          - service_error_rate < 1%
    pipelines:
      - id: github-actions-hr
        workflow: HR Module CI
        url: .github/workflows/hr-module-ci.yml
      - id: codex-template-smoke
        workflow: Codex Template Smoke
        url: .github/workflows/codex-template-smoke.yml
      - id: analytics-observability
        workflow: Terraform Compliance
        url: .github/workflows/terraform-compliance.yml
  - id: ai_ops_phase3
    name: AI Ops Automation
    description: Coordinate AI-driven reviews, trigger remediation playbooks, and surface telemetry for Phase3.
    actors:
      - role: ai_ops
        responsibilities:
          - review Codex Smoke output and LangGraph verification results
          - dispatch auto-remediation workflows when thresholds are breached
      - role: platform_pm
        responsibilities:
          - approve automated handoffs and communicate release readiness
    inputs:
      - type: workflow
        name: codex-template-smoke
      - type: workflow
        name: ai-ops-langgraph-verify
      - type: insights
        source: github_actions
        location: reports/ai-ops-insights.md
    outputs:
      - type: notification
        channels:
          - slack:#ai-ops-alerts
          - pagerduty:AI Ops Triage
      - type: dashboard
        url: docs/ai/ops-dashboard.md
    gates:
      - type: metric_watch
        thresholds:
          - codex_smoke_failure_rate < 5%
          - langgraph_verify_latency < 600s
      - type: approval
        approver: ai_ops_lead
        criteria:
          - remediation_playbook_attached
          - audit_log_updated
    pipelines:
      - id: ai-ops-langgraph
        workflow: AI Ops LangGraph Verify
        url: .github/workflows/ai-ops-langgraph-verify.yml
      - id: ai-ops-handoff
        workflow: AI Ops Auto Handoff
        url: .github/workflows/ai-ops-auto-handoff.yml
      - id: ai-ops-insights
        workflow: AI Ops Insights Publisher
        url: .github/workflows/ai-ops-insights.yml
