version: 1
metadata:
  owner: ai-dev-team
  reviewed_at: 2025-10-14
stages:
  - id: spec_authoring
    name: Spec Authoring
    description: Collect requirements, draft user stories, and define acceptance criteria.
    actors:
      - role: product_owner
        responsibilities:
          - approve scope
          - align stakeholders
      - role: ai_assistant
        responsibilities:
          - summarize domain context
          - propose user stories
    inputs:
      - type: issue
        format: github
        location: docs/specs/
    outputs:
      - type: markdown
        path: docs/specs/{feature}.md
    gates:
      - type: review
        reviewer: domain_lead
        criteria:
          - coverage_of_requirements
          - dependency_mapping
  - id: code_generation
    name: Code Generation & Scaffolding
    description: Use Codex CLI templates and project conventions to generate code skeletons.
    actors:
      - role: lead_engineer
        responsibilities:
          - seed repository structure
          - configure CI/CD hooks
      - role: ai_assistant
        responsibilities:
          - produce boilerplate code
          - suggest terraform modules
    inputs:
      - type: template
        source: templates/
    outputs:
      - type: pull_request
        branch_pattern: feature/{id}
    gates:
      - type: automatic_check
        check: lint
      - type: automatic_check
        check: unit_tests
  - id: test_and_review
    name: Automated Test & AI Review
    description: Execute automated tests and leverage AI reviewers before human approval.
    actors:
      - role: qa_engineer
        responsibilities:
          - define test coverage
          - triage failures
      - role: ai_reviewer
        responsibilities:
          - add PR comments
          - summarize risks
    inputs:
      - type: ci_workflow
        name: pull-request
    outputs:
      - type: report
        path: reports/{pr}.md
    gates:
      - type: ai_review
        provider: copilot
      - type: human_review
        reviewer: module_owner
  - id: documentation
    name: Documentation & Knowledge Share
    description: Ensure docs and runbooks stay in sync with shipped features.
    actors:
      - role: tech_writer
        responsibilities:
          - update runbooks
          - maintain API docs
      - role: ai_assistant
        responsibilities:
          - suggest doc diffs
    inputs:
      - type: repository
        path: docs/
    outputs:
      - type: pages_deploy
        url: https://itdojp.github.io/ITDO_ERP3
    gates:
      - type: doc_checklist
        items:
          - runbook_updated
          - api_diffs_linked
  - id: deployment
    name: Deployment & Observability
    description: Promote changes to staging/production with observability hooks.
    actors:
      - role: sre
        responsibilities:
          - manage terraform apply
          - monitor alarms
      - role: ai_ops
        responsibilities:
          - anomaly detection
          - rollback recommendation
    inputs:
      - type: pipeline
        tool: argo_cd
    outputs:
      - type: release_note
        path: docs/releases/{date}.md
    gates:
      - type: approval
        approver: release_manager
      - type: metric_watch
        thresholds:
          - service_error_rate < 1%
