version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"

  producer:
    build: ./producer
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - NUM_SHARDS=${NUM_SHARDS:-4}
      - PRODUCER_BATCH=${PRODUCER_BATCH:-100}
      - PRODUCER_RPS=${PRODUCER_RPS:-50}
      - USE_MINIO=${USE_MINIO:-false}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio}
      - MINIO_PORT=${MINIO_PORT:-9000}
      - MINIO_USE_SSL=${MINIO_USE_SSL:-false}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_BUCKET=${MINIO_BUCKET:-events}
    depends_on:
      - rabbitmq
      - minio

  consumer:
    build: ./consumer
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - NUM_SHARDS=${NUM_SHARDS:-4}
      - FAIL_RATE=${FAIL_RATE:-0.0}
    depends_on:
      - rabbitmq
      - redis

  pm-service:
    build: ./services/pm-service
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - NUM_SHARDS=${NUM_SHARDS:-4}
      - USE_MINIO=${USE_MINIO:-false}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio}
      - MINIO_PORT=${MINIO_PORT:-9000}
      - MINIO_USE_SSL=${MINIO_USE_SSL:-false}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_BUCKET=${MINIO_BUCKET:-events}
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
      - minio

  fi-service:
    build: ./services/fi-service
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - NUM_SHARDS=${NUM_SHARDS:-4}
      - PORT=3002
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
      - redis
