version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  producer:
    build: ./producer
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - NUM_SHARDS=${NUM_SHARDS:-4}
      - PRODUCER_BATCH=${PRODUCER_BATCH:-100}
      - PRODUCER_RPS=${PRODUCER_RPS:-50}
    depends_on:
      - rabbitmq

  consumer:
    build: ./consumer
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - NUM_SHARDS=${NUM_SHARDS:-4}
      - FAIL_RATE=${FAIL_RATE:-0.0}
    depends_on:
      - rabbitmq
      - redis

