apiVersion: 1
groups:
  - orgId: 1
    name: poc-telemetry
    folder: PoC Alerts
    interval: 1m
    rules:
      - uid: telemetry-fallback
        title: TelemetryFallbackSpike
        condition: C
        data:
          - refId: A
            datasourceUid: poc-loki
            model:
              datasource:
                type: loki
                uid: poc-loki
              editorMode: code
              expr: sum(count_over_time({job="poc-telemetry", event="mock_fallback"}[5m]))
              queryType: instant
              refId: A
          - refId: B
            datasourceUid: -100
            model:
              expression: A
              type: reduce
              reducer: last
          - refId: C
            datasourceUid: -100
            model:
              expression: B > 0
              type: math
        noDataState: OK
        execErrState: ALERTING
        for: 5m
        annotations:
          summary: "Telemetry fallback events detected"
        labels:
          severity: warning
