server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: poc-smoke
    static_configs:
      - targets: ['localhost']
        labels:
          job: poc-smoke
          __path__: /var/log/poc-smoke/*.log
  - job_name: poc-telemetry
    static_configs:
      - targets: ['localhost']
        labels:
          job: poc-telemetry
          __path__: /var/log/poc-smoke/telemetry.log*
