name: OpenAPI Lint

on:
  pull_request:
    paths:
      - 'openapi/**/*.yaml'
      - 'openapi/**/*.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Lint OpenAPI with Redocly
        run: npx --yes @redocly/cli@latest lint openapi/v1/openapi.yaml
