name: Podman Live Tests Notifications

on:
  workflow_run:
    workflows: ["Podman Live Playwright Tests"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ secrets.SLACK_WEBHOOK_URL != '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          RUN_CONCLUSION: ${{ github.event.workflow_run.conclusion }}
          RUN_URL: ${{ github.event.workflow_run.html_url }}
          RUN_DURATION: ${{ github.event.workflow_run.run_duration_ms }}
        run: |
          source scripts/lib/slack.sh
          case "$RUN_CONCLUSION" in
            success)
              status="success"
              title="Podman live tests passed"
              ;;
            failure|timed_out)
              status="failure"
              title="Podman live tests failed"
              ;;
            *)
              status="warning"
              title="Podman live tests conclusion: $RUN_CONCLUSION"
              ;;
          esac
          duration_minutes=0
          if [[ -n "$RUN_DURATION" ]]; then
            duration_minutes=$(python3 - <<'PY'
import os
value = os.environ.get("RUN_DURATION")
try:
    ms = int(value)
except Exception:
    ms = 0
minutes = ms / 60000
print(f"{minutes:.1f}")
PY
            )
          fi
          message="$title | duration=${duration_minutes}m"
          message+=" | details: $RUN_URL"
          slack_send "$status" "Podman Live Tests" "$message"
