name: Terraform Compliance Stack

on:
  pull_request:
    paths:
      - 'iac/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - stack: electronic-ledger
            workdir: iac/stacks/electronic-ledger
          - stack: billing-monitoring
            workdir: iac/stacks/billing-monitoring
    defaults:
      run:
        working-directory: ${{ matrix.workdir }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
      - name: Terraform fmt
        run: terraform fmt -check -recursive
      - name: Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan (electronic-ledger)
        if: matrix.stack == 'electronic-ledger'
        env:
          TF_VAR_aws_region: ap-northeast-1
          TF_VAR_ledger_bucket_name: demo-ledger-bucket
          TF_VAR_aws_account_id: "000000000000"
          TF_VAR_account_admin_arn: arn:aws:iam::000000000000:role/Dummy
          TF_VAR_skip_credentials_validation: "true"
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_DEFAULT_REGION: ap-northeast-1
          TF_VAR_environment: ci
        run: terraform plan -input=false -lock=false
      - name: Terraform plan (billing-monitoring)
        if: matrix.stack == 'billing-monitoring'
        env:
          TF_VAR_aws_region: ap-northeast-1
          TF_VAR_environment: ci
          TF_VAR_skip_credentials_validation: "true"
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_DEFAULT_REGION: ap-northeast-1
        run: terraform plan -input=false -lock=false
